### ISSUE TITLE
Guide: Document supported OSs

### ISSUE THREAD

**Issue by xbill82** [kuzzleio/kuzzle-guide#57]

**Comment by ballinette** [comment]
See draft: https://docs.google.com/document/d/12azGLQj-N0OJktx4veydhxw6DbTzpP2ML7gbnFIFWSU/edit#heading=h.rsshkuyocgr

Also remove "Windows install" from documentation

**Comment by dbengsch** [comment]
Issue moved to [kuzzleio/documentation #44](https://github.com/kuzzleio/documentation/issues/44) via [**ZenHub**](https://www.zenhub.com/)
