### ISSUE TITLE
Guide: Issue related to "User guide/Security/Permissions" section

### ISSUE THREAD

**Issue by scottinet** [kuzzleio/kuzzle-guide#81]
Documentation of roles definition should mention that plugin controllers can also be added with the following format:

```js
{
  controllers: {
    "<plugin name>/<exposed controller name>": {
      actions: {
        "<exposed controller action>": true
      }
    }
  }
}
```

**Comment by dbengsch** [comment]
Issue moved to [kuzzleio/documentation #46](https://github.com/kuzzleio/documentation/issues/46) via [**ZenHub**](https://www.zenhub.com/)
