### ISSUE TITLE
Guide: Issue related to "Plugins/Creating plugins/> Protocol plugins" section

### ISSUE THREAD

**Issue by scottinet** [kuzzleio/kuzzle-guide#88]
This section should have its own documentation, separated from the Kuzzle plugins one, for the following reasons:

* its plugin context is different from the one received by other plugins
* protocol plugins are installed by Kuzzle Proxy, not Kuzzle Server. A specific protocol plugin install guide should also be added

**Comment by dbengsch** [comment]
Issue moved to [kuzzleio/documentation #47](https://github.com/kuzzleio/documentation/issues/47) via [**ZenHub**](https://www.zenhub.com/)
