### ISSUE TITLE
Guide: Plugins: document that plugins' init functions can throw

### ISSUE THREAD

**Issue by scottinet** [kuzzleio/kuzzle-guide#97]
We should mention that plugins may throw exceptions during their initialization phase to signal, for instance, an invalid configuration. And that Kuzzle handles this case by logging an error and pursuing its own initialization by excluding the plugin.

**Comment by dbengsch** [comment]
Issue moved to [kuzzleio/documentation #51](https://github.com/kuzzleio/documentation/issues/51) via [**ZenHub**](https://www.zenhub.com/)
